In [1]:
!python --version

Python 3.13.7


# PyTorch Introduction

This tutorial is based on the excellent tutorial from the [PyTorch website](https://pytorch.org/tutorials/beginner/basics/intro.html), written by Suraj Subramanian, Seth Juarez, Cassie Breviu, Dmitry Soshnikov and Ari Bornstein.

## Tensors

+ Tensors are essentially **multidimensional arrays**.
+ Used in `PyTorch` to encode model inputs, outputs, and parameters.
+ Similar to NumPy’s `ndarrays` but can run on **GPUs and hardware accelerators**.
+ Tensors and NumPy arrays can share the same memory, avoiding data copying.
+ Optimized for **automatic differentiation**.

In [2]:
import torch
import numpy as np

Creating a tensor from a multidimensional Python array:

In [3]:
x = [[1, 2], [3, 4], [5, 6]]

x_torch = torch.tensor(x)
x_torch

tensor([[1, 2],
        [3, 4],
        [5, 6]])

... which is akin to how we create numpy arrays:

In [4]:
x_np = np.array(x)
x_np

array([[1, 2],
       [3, 4],
       [5, 6]])

We can create a torch tensor directly from a numpy array, which shares the same memory:

In [5]:
x_torch_from_np = torch.from_numpy(x_np)
x_torch_from_np

tensor([[1, 2],
        [3, 4],
        [5, 6]])

We can also convert a tensor to a numpy array using the `.numpy()` method.

In [6]:
x_torch.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

### Tensor attributes: `dtype`, `shape`, and `device`

Tensors have a `dtype` attribute that specifies the data type of the elements in the tensor.

Since the original list contains integers, the tensor is of type `torch.int64` (type inference).
The default type is `torch.float32`.

In [7]:
x_torch.dtype

torch.int64

If we create a tensor from a list of *floats*, the tensor will be of type `torch.float32`:

In [8]:
x_torch = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])
x_torch.dtype

torch.float32

We can explictly set the dtype when constructing a tensor:

In [ ]:
x_torch = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64)
x_torch.dtype

Like in `numpy`, each torch tensor has a `shape` attribute that describes the size of each dimension of the tensor.

In [9]:
x_torch = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])
print(x_torch)
print(f'\nShape: {x_torch.shape}')

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

Shape: torch.Size([3, 2])


i.e., `x_torch` $\in \mathbb{R}^{3 \times 2}$

By default, `torch` tensors are created on the CPU.
We can check which device the tensor is on using the `.device` attribute.

In [10]:
x_torch.device

device(type='cpu')

If we have a GPU, we can move it to the GPU using the `to` method:

In [11]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

x_torch = x_torch.to(DEVICE)
x_torch.device

device(type='cpu')

### Creating Tensors with default values

There are other convenient ways to create tensors:

In [ ]:
ones = torch.ones(3, 2)
ones

In [ ]:
zeros = torch.zeros(3, 2)
zeros

In [12]:
normal_samples = torch.randn(3, 2)
normal_samples

tensor([[-0.4186, -0.5653],
        [-0.5925, -0.2383],
        [-0.6430, -1.2140]])

In [13]:
arange = torch.arange(6.)
arange

tensor([0., 1., 2., 3., 4., 5.])

If we already have a tensor and we want to create a new tensor with the same `shape`, `dtype`, and `device`, we can use the following methods:

In [14]:
ones = torch.ones_like(x_torch)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
zeros = torch.zeros_like(x_torch)
normal_samples = torch.randn_like(x_torch)

### Reshaping


In [ ]:
arange = torch.arange(8.)
print(arange)
print(f'\nShape: {arange.shape}')

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
<built-in method type of Tensor object at 0x1111c9040>

Shape: torch.Size([8])


In [16]:
arange = arange.reshape(4, 2)
arange

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.]])

In [ ]:
arange = arange.reshape(2, 2, 2)
arange

### Indexing

In [20]:
tensor = torch.arange(16.).reshape(4, 4)
tensor

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

Indexing works the same way as in `numpy`:

In [21]:
tensor[2, 1]

tensor(9.)

In [ ]:
print(f"First row: {tensor[0, :]}")
print(f"First column: {tensor[:, 0]}")
print(f"Second column: {tensor[:, 1]}")
print(f"Last column: {tensor[:, -1]}")

### Operations

In [22]:
tensor

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

[Broadcast operation](https://pytorch.org/docs/stable/notes/broadcasting.html):

In [23]:
t2 = tensor + 1.5
t2

tensor([[ 1.5000,  2.5000,  3.5000,  4.5000],
        [ 5.5000,  6.5000,  7.5000,  8.5000],
        [ 9.5000, 10.5000, 11.5000, 12.5000],
        [13.5000, 14.5000, 15.5000, 16.5000]])

Add two tensors of same shape:

In [24]:
tensor + t2

tensor([[ 1.5000,  3.5000,  5.5000,  7.5000],
        [ 9.5000, 11.5000, 13.5000, 15.5000],
        [17.5000, 19.5000, 21.5000, 23.5000],
        [25.5000, 27.5000, 29.5000, 31.5000]])

Component-wise product:

In [25]:
tensor * t2

tensor([[  0.0000,   2.5000,   7.0000,  13.5000],
        [ 22.0000,  32.5000,  45.0000,  59.5000],
        [ 76.0000,  94.5000, 115.0000, 137.5000],
        [162.0000, 188.5000, 217.0000, 247.5000]])

We can *transpose* the tensor using the `T` method:

In [26]:
print(tensor)
print('\n')
print(tensor.T)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


tensor([[ 0.,  4.,  8., 12.],
        [ 1.,  5.,  9., 13.],
        [ 2.,  6., 10., 14.],
        [ 3.,  7., 11., 15.]])


Matrix multiply:

In [27]:
tensor.T @ tensor

tensor([[224., 248., 272., 296.],
        [248., 276., 304., 332.],
        [272., 304., 336., 368.],
        [296., 332., 368., 404.]])

### Aggregation functions

In [28]:
print(f'Sum: {torch.sum(tensor)}')
print(f'Product: {torch.prod(tensor)}')
print(f'Max: {torch.max(tensor)}')
print(f'Min: {torch.min(tensor)}')
print(f'Mean: {torch.mean(tensor)}')

Sum: 120.0
Product: 0.0
Max: 15.0
Min: 0.0
Mean: 7.5


We can aggregate values over certain dimensions:

In [29]:
tensor

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [30]:
tensor.shape

torch.Size([4, 4])

In [31]:
col_sums = torch.sum(tensor, dim=0)
col_sums

tensor([24., 28., 32., 36.])